### ISSUE TITLE
2409

### ISSUE THREAD

**Issue by gurselalp** [TRvACC/LTXX-Sector-File#2]
- [x] LTAI Taxiway E2 needs to be added.
- [x] LTFE 28R ATIS must be revised to ILS Z

[LT_Amdt_A_2024_07_en](https://drive.google.com/file/d/1u59Zf0Wi_4iYn-6gDd0Nhi9TtKvn0nYv/view?usp=drive_link)

**Comment by gurselalp** [comment]
#3 Text added into TopSkymaps for ACC-APP

**Comment by HazarMelihUymaz** [comment]
[vATIS Profile - ANK_CTR (30.08.24).json](https://github.com/user-attachments/files/16820130/vATIS.Profile.-.ANK_CTR.30.08.24.json)
[vATIS Profile - LTBB (30.08.24).json](https://github.com/user-attachments/files/16820131/vATIS.Profile.-.LTBB.30.08.24.json)

LTFE 28R ATIS revised to ILS Z
(This file couldn't uploads from GitHub Desktop)

**Comment by HazarMelihUymaz** [comment]
Profiles uploaded to GNG
@gurselalp
